CalendarSynchronizerWeb/CalendarSynchronizerWeb/ViewModels/Schedule/ScheduleUpdateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CalendarSynchronizerWeb.ViewModels.Schedule
{
    public class ScheduleUpdateViewModel
    {
        [Required]
        public Guid Id { get; set; }
        public string Subject { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime? StartTime { get; set; }
        public string StartTimeZone { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime? EndTime { get; set; }
        public string EndTimeZone { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public bool IsAllDay { get; set; } = false;
        public string? CalendarId { get; set; }
    }
}

CalendarSynchronizerWeb/CalendarSynchronizerWeb/ViewModels/Schedule/ScheduleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CalendarSynchronizerWeb.ViewModels.Schedule
{
    public class ScheduleViewModel
    {
        public Guid? Id { get; set; }
        public string? Subject { get; set; }
        [Required]
        //[DataType(DataType.DateTime)]
        public DateTime? StartTime { get; set; }
        public string? StartTimeZone { get; set; }
        [Required]
        //[DataType(DataType.DateTime)]
        public DateTime? EndTime { get; set; }
        public string? EndTimeZone { get; set; }
        public string? Status { get; set; }
        public string? Description { get; set; }
        public string? Location { get; set; }
        public bool IsAllDay { get; set; } = false;
        public string? CalendarId { get; set; }

    }
}

CalendarSynchronizerWeb/CalendarSynchronizerWeb/Controllers/ScheduleController.cs
using BLL.Intrfaces;
using CalendarSynchronizerWeb.Models;
using CalendarSynchronizerWeb.ViewModels.Schedule;
using Core.Models;
using Google.Apis.Calendar.v3.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Globalization;

namespace CalendarSynchronizerWeb.Controllers
{
    [Authorize(Roles = "User, Admin")]
    public class ScheduleController : Controller
    {
        private readonly IScheduleService scheduleService;
        private readonly ILogger<ScheduleController> logger;
        private readonly IHttpContextAccessor httpContextAccessor;

        public ScheduleController(ILogger<ScheduleController> logger, IScheduleService scheduleService, IHttpContextAccessor httpContextAccessor)
        {
            this.logger = logger;
            this.scheduleService = scheduleService;
            this.httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index(string calendarId, string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["StartTimeSortParam"] = String.IsNullOrEmpty(sortOrder) ? "startTime_desc" : "";
            ViewData["EndTimeSortParam"] = sortOrder == "EndTime" ? "endTime_desc" : "EndTime";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            try
            {
                if (calendarId == null)
                {
                    httpContextAccessor.HttpContext.Request.Cookies.TryGetValue("calendarId", out calendarId);
                }
                else
                {
                    httpContextAccessor.HttpContext.Response.Cookies.Append("calendarId", calendarId);
                }
                var schedules = await scheduleService.GetCalendarSchedules(calendarId, searchString, sortOrder);

                int pageSize = 3;
                return View(CalendarPaginatedList<Schedule>.CreateAsync(schedules, pageNumber ?? 1, pageSize));
            }
            catch (Exception e)
            {
                logger.LogError(e.Message);
                return View("Error");
            }
        }

        // GET: ScheduleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ScheduleController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ScheduleViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string? id;
                    httpContextAccessor.HttpContext.Request.Cookies.TryGetValue("calendarId", out id);
                    if (id == null)
                    {
                        return View("Error");
                    }

                    var schedule = transfromViewModelToModel(viewModel);
                    schedule.CalendarId = id;
                    await scheduleService.Create(schedule);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    logger.LogError(ex.Message);
                    return View();
                }
            }

            return View(viewModel);
        }

        public async Task<IActionResult> Details(Guid scheduleId)
        {
            var schedule = await scheduleService.GetSchedule(scheduleId);

            if (schedule == null)
            {
                return RedirectToAction(nameof(Index));
            }

            ScheduleViewModel viewModel = transfromModelToViewModel(schedule);
            return View(viewModel);

        }

        // GET: ScheduleController/Edit/5
        public async Task<IActionResult> Edit(Guid scheduleId)
        {
            var schedule = await scheduleService.GetSchedule(scheduleId);

            if (schedule == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var viewModel = transfromModelToViewModel(schedule);

            return View(viewModel);
        }

        // POST: ScheduleController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ScheduleUpdateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string? id;
                    httpContextAccessor.HttpContext.Request.Cookies.TryGetValue("calendarId", out id);
                    var schedule = transfromViewModelToModel(viewModel);

                    if (id == null)
                    {
                        return Redirect("Error");
                    }

                    schedule.CalendarId = id;
                    await scheduleService.Update(schedule.Id, schedule);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    logger.LogError(e.Message);
                    return View();
                }
            }

            return View(viewModel);
        }

        // POST: ScheduleController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid scheduleId)
        {
            try
            {
                await scheduleService.Delete(scheduleId);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                logger.LogError(e.Message);
                return View();
            }
        }

        private Schedule transfromViewModelToModel(ScheduleViewModel viewModel)
        {
            return new Schedule
            {
                Subject = viewModel.Subject ?? "none",
                StartTime = viewModel.StartTime,
                EndTime = viewModel.EndTime,
                StartTimezone = viewModel.EndTimeZone ?? "none",
                EndTimezone = viewModel.EndTimeZone ?? "none",
                Status = viewModel.Status ?? "none",
                Description = viewModel.Description ?? "none",
                Location = viewModel.Location ?? "none",
                IsAllDay = viewModel.IsAllDay,
            };
        }

        private Schedule transfromViewModelToModel(ScheduleUpdateViewModel viewModel)
        {
            return new Schedule
            {
                Id = viewModel.Id,
                Subject = viewModel.Subject,
                StartTime = viewModel.StartTime,
                EndTime = viewModel.EndTime,
                StartTimezone = viewModel.EndTimeZone,
                EndTimezone = viewModel.EndTimeZone,
                Status = viewModel.Status,
                Description = viewModel.Description,
                Location = viewModel.Location,
                IsAllDay = viewModel.IsAllDay
            };
        }

        private ScheduleViewModel transfromModelToViewModel(Schedule model)
        {
            return new ScheduleViewModel
            {
                Id = model.Id,
                Subject = model.Subject,
                StartTime = model.StartTime,
                EndTime = model.EndTime,
                StartTimeZone = model.StartTimezone,
                EndTimeZone = model.EndTimezone,
                Status = model.Status,
                Description = model.Description,
                Location = model.Location,
                IsAllDay = model.IsAllDay,
                CalendarId = model.CalendarId
            };
        }
    }
}

CalendarSynchronizerWeb/CalendarSynchronizerWeb/Views/Schedule/Create.cshtml
@using CalendarSynchronizerWeb.ViewModels.Schedule
@model ScheduleViewModel

@{
    var title = "Create Event";
}

<form method="post">
    @*    @if (Model != null && !String.IsNullOrEmpty(Model.CalendarId))
    {
    title = "Edit Role";
    <input asp-for="@Model.Id" hidden />
    }*@

    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Id"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Id" readonly class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Subject"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Subject" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Subject" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="StartTime"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StartTime" class="form-control" autocomplete="off" />
                        <span asp-validation-for="StartTime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="StartTimeZone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StartTimeZone" class="form-control" autocomplete="off" />
                        <span asp-validation-for="StartTimeZone" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="EndTime"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EndTime" class="form-control" autocomplete="off" />
                        <span asp-validation-for="EndTime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="EndTimeZone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EndTimeZone" class="form-control" autocomplete="off" />
                        <span asp-validation-for="EndTimeZone" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Status"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Status" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Location"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Location" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Location" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="IsAllDay"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="IsAllDay" class="form-control" autocomplete="off" />
                        <span asp-validation-for="IsAllDay" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            @if (Model != null && !String.IsNullOrEmpty(Model.CalendarId))
                            {
                            //update
                                <input type="submit" class="btn btn-info w-100" value="Update" />
                            }
                            else
                            {
                                //create
                                <input type="submit" class="btn btn-primary w-100" value="Create" />
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

CalendarSynchronizerWeb/CalendarSynchronizerWeb/Views/Schedule/Details.cshtml
@using CalendarSynchronizerWeb.ViewModels.Schedule
@model ScheduleViewModel


<h1>Event Details: </h1>
<div class="border border-primary border-4 p-3">
    <div class="m-3 p-1 border-bottom border-secondary border-2">
        <p>Event Id</p>
        <p> @Model.Id</p>
    </div>
    <div class="m-3 p-1 border-bottom border-secondary border-2">
        <p>Event Description</p>
        <p> @Model.Description</p>
    </div>
    <div class="m-3 p-1 border-bottom border-secondary border-2">
        <p>Time start</p>
        <p> @Model.StartTime</p>

    </div>
    <div class="m-3 p-1 border-bottom border-secondary border-2">
        <p>Zone Start</p>
        <p> @Model.StartTimeZone</p>
    </div>
    <div class="m-3 p-1 border-bottom border-secondary border-2">
        <p>Time start</p>
        <p> @Model.EndTime</p>

    </div>
    <div class="m-3 p-1 border-bottom border-secondary border-2">
        <p>Zone Start</p>
        <p> @Model.EndTimeZone</p>
    </div>

    <a asp-controller="Schedule" asp-action="Index" class="btn btn-danger">Back</a>
</div>

CalendarSynchronizerWeb/CalendarSynchronizerWeb/Views/Schedule/Edit.cshtml
@using CalendarSynchronizerWeb.ViewModels.Schedule
@model ScheduleViewModel

@{
    var title = "Update Event";
}

<form method="post">

    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Id"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Id" readonly class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Subject"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Subject" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Subject" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="StartTime"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StartTime" class="form-control" autocomplete="off" />
                        <span asp-validation-for="StartTime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="StartTimeZone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="StartTimeZone" class="form-control" autocomplete="off" />
                        <span asp-validation-for="StartTimeZone" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="EndTime"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EndTime" class="form-control" autocomplete="off" />
                        <span asp-validation-for="EndTime" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="EndTimeZone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="EndTimeZone" class="form-control" autocomplete="off" />
                        <span asp-validation-for="EndTimeZone" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Status"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Status" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Location"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Location" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Location" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="IsAllDay"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="IsAllDay" class="form-control" autocomplete="off" />
                        <span asp-validation-for="IsAllDay" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            
                                <input type="submit" class="btn btn-info w-100" value="Update" />
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

CalendarSynchronizerWeb/CalendarSynchronizerWeb/Views/Schedule/Index.cshtml
@using Core.Models

@model CalendarPaginatedList<Schedule>

<br />
<div class="row">
    <div>
        <div class="col-6">
            <h2 class="text-primary"> Your Events </h2>
        </div>
        <div class="col-6">
            <h2 class="text-primary">Calendar Summary @if(Model.Any()){ @Model.ToList()[0].Calendar.Summary }</h2>
        </div>
    </div>
    <div class="col-6 text-right">
        <a asp-action="Create" asp-controller="Schedule" asp-route-calendarId="" class="btn btn-primary">Create New Event</a>
    </div>
</div>
<form asp-controller="Schedule" asp-action="Index" method="get">
    <p>
        Subject: <input type="text" name="searchString" value="@ViewData["CurrentFilter"]" />
        <input class="btn btn-secondary" type="submit" value="Search" /> |
        <a asp-action="Index">Back to Full List</a>
    </p>
</form>
<div class="p-4 border rounded">
    @if (Model.Count() > 0)
    {
        <table class="table table-striped border">
            <tr class="table-secondary">
                <th>
                    Schedule Id
                </th>
                <th>
                    Subject
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["StartTimeSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Start Time</a>
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["EndTimeSortParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">End Time</a>
                    End Time
                </th>
                <th>Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.CalendarId
                    </td>
                    <td>
                        @item.Subject
                    </td>
                    <td>
                        @item.StartTime
                    </td>
                    <td>
                        @item.EndTime
                    </td>
                    <td>
                        <div class="text-center">
                            <form asp-action="Delete" asp-route-scheduleId="@item.Id">
                                <a asp-action="Edit" asp-route-scheduleId="@item.Id" class="btn btn-info text-white">
                                    Edit
                                </a>
                                <a asp-action="Details" asp-route-scheduleId="@item.Id" class="btn btn-secondary text-white">Details</a>
                                <button type="submit" onclick="return confirm('Are you sure you want to delete this?')"
                                class="btn btn-danger">
                                    Delete
                                </button>
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </table>
    }
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>
</div>