CalendarSynchronizerWeb/CalendarSynchronizerWeb/Controllers/GoogleCalendarController.cs
using BLL.Managers.Interfaces;
using Core.Models;
using DAL;
using Microsoft.AspNetCore.Mvc;
using Core.Interfaces;
using CalendarSynchronizerWeb.Extensions;
using Google.Apis.Calendar.v3.Data;
using CalendarSynchronizerWeb.Services;
using Google.Apis.Calendar.v3;
using Google.Apis.Services;
using CalendarSynchronizerWeb.ViewModels.Calendar;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using BLL.Intrfaces;

namespace CalendarSynchronizerWeb.Controllers
{
    public class GoogleCalendarController : Controller
    {
        private readonly IConfigurationManager<GoogleAuthCreds> _configurationManager;
        private readonly ApplicationDbContext _context;
        private readonly IRepository<Schedule> _repository;
        private string calendarId = "test.calendar.google.com";
        private readonly CalendarService calendarService;
        private readonly IGoogleCalendarService service;

        public GoogleCalendarController(IConfigurationManager<GoogleAuthCreds> configurationManager, ApplicationDbContext context, IGoogleCalendarService service)
        {
            _configurationManager = configurationManager;
            _context = context;
            this.calendarService = new CalendarService(new BaseClientService.Initializer
            {
                HttpClientInitializer = new CustomUserCredential(_configurationManager.Value.AccessToken),
                ApplicationName = "CalendarSynchronizer"
            });
            this.service = service;
        }

        public async Task<IActionResult> Index()
        {
            CalendarList list = await calendarService.CalendarList.List().ExecuteAsync();
            var calendarsFromGoogle = list.Items;
            List<CalendarMy> calendars = new List<CalendarMy>();    
            foreach(var item in calendarsFromGoogle)
            {
                calendars.Add(new CalendarMy
                {
                    CalendarId = item.Id,
                    Summary = item.Summary,
                    Description = item.Description,
                    TimeZone = item.TimeZone,
                });
            }

            return View(calendars);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CalendarViewModel viewModel)
        {
            if (ModelState.IsValid) {
                Calendar newCalendar = new Calendar()
                {
                    Summary =viewModel.Summary,
                    Description=viewModel.Description,
                    TimeZone=viewModel.TimeZone,
                };
                CalendarsResource.InsertRequest request = calendarService.Calendars.Insert(newCalendar);
                Calendar calendar = request.Execute();
                return RedirectToAction(nameof(Index));
            }

            return View("Error");
        }

        public async Task InitialSync(/*calendarId param*/)
        {
            //GoogleCalendarService service = new GoogleCalendarService(_configurationManager);
            var res1 = await service.GetAllCalendarListAsync();

            var res = await service.GetCalendarEventsList(calendarId);

            _configurationManager.ChangeAppSettingValue(opt => opt.SyncToken = res.NextSyncToken);

            foreach (var r in res.Items)
            {
                if (r.Status == "cancelled")
                {
                    continue;
                }
                await _repository.CreateAsync(new Schedule
                {
                    Description = r.Description,
                    StartTime = r.Start.DateTime.HasValue ? r.Start.DateTime.Value : DateTime.Parse(r.Start.Date),
                    EndTime = r.End.DateTime.HasValue ? r.End.DateTime.Value : DateTime.Parse(r.End.Date),
                    StartTimezone = r.Start.TimeZone,
                    Status = r.Status,
                    EndTimezone = r.End.TimeZone,
                    ExternalId = r.Id,
                    Location = r.Location,
                    RecurrenceID = r.RecurringEventId,
                    RecurrenceRule = r.Recurrence is null ? String.Empty : String.Concat(r.Recurrence.SelectMany(s => s)),
                    RecurrenceException = String.IsNullOrEmpty(r.RecurringEventId) ? String.Empty : r.Start.DateTime.HasValue ? r.Start.DateTime.Value.ToString("yyyyMMddTHHmmssZ") : Convert.ToDateTime(r.Start.Date).ToString("yyyyMMddTHHmmssZ"),
                    IsAllDay = !String.IsNullOrEmpty(r.Start.Date),
                    Subject = r.Summary
                });
            }



        }
        public async Task Sync(/*calendarId param*/)
        {
            if (!await _repository.Any())
            {
                return;
            }
            //GoogleCalendarService service = new GoogleCalendarService(_configurationManager);
            var res1 = await service.GetAllCalendarListAsync();

            var res = await service.GetCalendarEventsList(calendarId);

            var fromDb = await _repository.GetAllAsync();

            var fromServer = new List<Schedule>();

            foreach (var r in res.Items)
            {
                fromServer.Add(new Schedule
                {
                    Description = r.Description,
                    StartTime = r.Start.DateTime.HasValue ? r.Start.DateTime.Value : DateTime.Parse(r.Start.Date),
                    EndTime = r.End.DateTime.HasValue ? r.End.DateTime.Value : DateTime.Parse(r.End.Date),
                    StartTimezone = r.Start.TimeZone,
                    Status = r.Status,
                    EndTimezone = r.End.TimeZone,
                    ExternalId = r.Id,
                    Location = r.Location,
                    RecurrenceID = r.RecurringEventId,
                    RecurrenceRule = r.Recurrence is null ? String.Empty : String.Concat(r.Recurrence.SelectMany(s => s)),
                    RecurrenceException = String.IsNullOrEmpty(r.RecurringEventId) ? String.Empty : r.Start.DateTime.HasValue ? r.Start.DateTime.Value.ToString("yyyyMMddTHHmmssZ") : Convert.ToDateTime(r.Start.Date).ToString("yyyyMMddTHHmmssZ"),
                    IsAllDay = !String.IsNullOrEmpty(r.Start.Date),
                    Subject = r.Summary
                });
            }

            fromDb.Sort(new ScheduleComparer());
            fromServer.Sort(new ScheduleComparer());
            //s - from google, t - from db

            var diff = fromServer.ZipEqual(fromDb, new ScheduleComparer(), (s, t) =>
            {
                if (s == null) return new ScheduleStateChanged { Target = t, Action = State.Delete };

                if (t == null) return new ScheduleStateChanged { Source = s, Action = State.Create };

                return new ScheduleStateChanged { Source = s, Target = t, Action = State.Update };
            });

            await _repository.HandleScheduleStatesAsync(diff);
            ;




        }

        public async Task IncrementalSync(/*calendarId param*/)
        {
            //GoogleCalendarService service = new GoogleCalendarService(_configurationManager);

            var calendar = service.GetCalenderService(); //TODO: refactor this trash

            var request = calendar.Events.List(calendarId);



            string pageToken = null;
            string syncToken = _configurationManager.Value.SyncToken;
            Events events = null;
            List<Event> result = new List<Event>();

            if (syncToken == "default")
            {
                //do full sync 
                ;
            }
            else
            {
                request.SyncToken = syncToken;
            }

            do
            {
                request.PageToken = pageToken;

                events = await request.ExecuteAsync();



                //syncEvent(event);


                var fromDb = await _repository.GetAllAsync();

                var fromServer = new List<Schedule>();


                foreach (var r in events.Items)
                {
                    if (r.Status == "cancelled")
                    {
                        fromServer.Add(new Schedule
                        {
                            ExternalId = r.Id,
                            RecurrenceID = r.RecurringEventId,
                            RecurrenceRule = r.Recurrence is null ? String.Empty : String.Concat(r.Recurrence.SelectMany(s => s)),
                            Status = r.Status

                        });
                    }
                    else
                    {
                        fromServer.Add(new Schedule
                        {
                            Description = r.Description,
                            StartTime = r.Start.DateTime.HasValue ? r.Start.DateTime.Value : DateTime.Parse(r.Start.Date),
                            EndTime = r.End.DateTime.HasValue ? r.End.DateTime.Value : DateTime.Parse(r.End.Date),
                            StartTimezone = r.Start.TimeZone,
                            Status = r.Status,
                            EndTimezone = r.End.TimeZone,
                            ExternalId = r.Id,
                            Location = r.Location,
                            RecurrenceID = r.RecurringEventId,
                            RecurrenceRule = r.Recurrence is null ? String.Empty : String.Concat(r.Recurrence.SelectMany(s => s)),
                            RecurrenceException = String.IsNullOrEmpty(r.RecurringEventId) ? String.Empty : r.Start.DateTime.HasValue ? r.Start.DateTime.Value.ToString("yyyyMMddTHHmmssZ") : Convert.ToDateTime(r.Start.Date).ToString("yyyyMMddTHHmmssZ"),
                            IsAllDay = !String.IsNullOrEmpty(r.Start.Date),
                            Subject = r.Summary
                        });
                    }
                    //result.Add(item);
                }


                var diff = fromServer.ZipEqual(fromDb, new ScheduleComparer(), (s, t) =>

CalendarSynchronizerWeb/CalendarSynchronizerWeb/Views/GoogleCalendar/Create.cshtml
@using CalendarSynchronizerWeb.ViewModels.Calendar;
@model CalendarViewModel

@{
    var title = "Create Calendar";
}

<form method="post">
    @if (Model != null && !String.IsNullOrEmpty(Model.CalendarId))
    {
        title = "Edit Role";
        <input asp-for="@Model.CalendarId" hidden />
    }

    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="CalendarId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="CalendarId" readonly class="form-control" />
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Summary"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Summary" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Summary" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-4">
                        <label asp-for="TimeZone"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TimeZone" class="form-control" autocomplete="off" />
                        <span asp-validation-for="TimeZone" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2 ">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-primary w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>

CalendarSynchronizerWeb/CalendarSynchronizerWeb/Views/GoogleCalendar/Index.cshtml
@using Core.Models
@model IEnumerable<CalendarMy>

<br />
<h1>
    Google Calendar Page
</h1>
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">All Calendars List </h2>
    </div>
    <div class="col-6 text-right">
        <a asp-action="Create" asp-controller="GoogleCalendar" class="btn btn-primary">Create New Calendar</a>
</    div>
</div>
<div class="p-4 border rounded">
    @if (Model.Count() > 0)
    {
        <table class="table table-striped border">
            <tr class="table-secondary">
                <th>
                    CalendarId
                </th>
                <th>
                    Summary
                </th>
                <th>
                    Description
                </th>
                <th>
                    Time Zone
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.CalendarId
                    </td>
                    <td>
                        @item.Summary
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.TimeZone
                    </td>
                </tr>
            }
        </table>
    }
</div>